#!/usr/bin/env bash
# =============================================================================
# NASX — sudo setup script
# =============================================================================
# Installs a sudoers rule so the backend process can:
#   1. Impersonate any Linux user for file operations (ls, mkdir, copy, …)
#   2. Run chmod / chown as root for permission management
#
# Usage:
#   sudo ./scripts/setup-sudo.sh [BACKEND_USER]
#
#   BACKEND_USER  User the backend process runs as. Default: nasx
#                 Use "$(whoami)" to use the current user.
#
# Examples:
#   sudo ./scripts/setup-sudo.sh
#   sudo ./scripts/setup-sudo.sh theophile
# =============================================================================

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[info]${NC}  $*"; }
success() { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()     { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── args ─────────────────────────────────────────────────────────────────────
BACKEND_USER="${1:-nasx}"

SUDOERS_FILE="/etc/sudoers.d/nasx"

# ── must run as root ──────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run this script with sudo: sudo $0 $*"

# ── verify backend user exists ────────────────────────────────────────────────
if ! id "$BACKEND_USER" &>/dev/null; then
  die "User '$BACKEND_USER' does not exist.\n  Create it first:\n    useradd -r -m -s /usr/sbin/nologin $BACKEND_USER"
fi

# ── locate fs-helper binary ──────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FS_HELPER_BIN="$REPO_ROOT/bin/fs-helper"

if [[ ! -x "$FS_HELPER_BIN" ]]; then
  die "fs-helper binary not found or not executable at:\n  $FS_HELPER_BIN"
fi

FS_HELPER_BIN="$(realpath "$FS_HELPER_BIN")"

# ── summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${CYAN}NASX sudo setup${NC}"
echo    "  ────────────────────────────────────────────"
info   "Backend user : $BACKEND_USER"
info   "fs-helper    : $FS_HELPER_BIN"
info   "Sudoers file : $SUDOERS_FILE"
echo ""

# ── write sudoers rule ────────────────────────────────────────────────────────
# One rule covers everything:
#   - impersonation: sudo -u <linuxUser> <fs-helper> <op> <args>
#   - root ops:      sudo              <fs-helper> chmod/chown <args>
# Both match "(ALL)" which includes root.

cat > "$SUDOERS_FILE" <<EOF
# NASX backend sudo rules
# Generated by setup-sudo.sh on $(date)
# Do not edit manually — re-run setup-sudo.sh to regenerate.

# Allow the backend process ($BACKEND_USER) to run the fs-helper as any user.
# This covers both Linux-user impersonation (file ops) and root (chmod/chown).
$BACKEND_USER ALL = (ALL) NOPASSWD: $FS_HELPER_BIN *
EOF

chmod 0440 "$SUDOERS_FILE"

# ── validate ──────────────────────────────────────────────────────────────────
if command -v visudo &>/dev/null; then
  if visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    success "Sudoers rule validated."
  else
    rm -f "$SUDOERS_FILE"
    die "Sudoers validation failed — file removed. Run 'visudo -c -f $SUDOERS_FILE' for details."
  fi
else
  warn "visudo not found — skipping validation. Review $SUDOERS_FILE manually."
fi

success "Sudoers rule installed at $SUDOERS_FILE"
echo ""
echo -e "  ${GREEN}Done.${NC} The NASX backend can now:"
echo    "    • Run file operations (list/mkdir/copy/move/delete) as any Linux user"
echo    "    • Run chmod and chown as root"
echo ""
echo    "  To remove these rules:"
echo -e "    ${CYAN}sudo rm $SUDOERS_FILE${NC}"
echo ""

# ── optional: verify it works ─────────────────────────────────────────────────
if [[ "${VERIFY:-0}" == "1" ]]; then
  info "Verifying rule (VERIFY=1)…"
  if sudo -u "$BACKEND_USER" sudo -n "$FS_HELPER_BIN" stat / &>/dev/null; then
    success "Test run succeeded."
  else
    warn "Test run failed. Check that $BACKEND_USER can sudo without a password."
  fi
fi
